security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: userId
    firewalls:
       
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # ...
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            lazy: true
            logout:
                path: app_logout
                target: index
    role_hierarchy:
        ROLE_Magasinier: [ROLE_TeamLeader]
        ROLE_Client: [ROLE_Utilisateur]
        ROLE_TeamLeader: [ROLE_Client]
    access_control: